apiVersion: cert-platform.io/v1alpha1
kind: GradingCheck
metadata:
  questionId: cka-q003
spec:
  targetCluster: cka-kind
  namespace: edge-web
  maxScore: 10
  checks:
    - id: ingress-exists
      type: kubernetes-object-exists
      points: 2
      object:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: orders-ingress
    - id: ingress-class
      type: jsonpath-equals
      points: 2
      object:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: orders-ingress
      path: $.spec.ingressClassName
      equals: nginx
    - id: ingress-host
      type: jsonpath-equals
      points: 2
      object:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: orders-ingress
      path: $.spec.rules[0].host
      equals: orders.internal.local
    - id: ingress-path
      type: jsonpath-equals
      points: 1
      object:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: orders-ingress
      path: $.spec.rules[0].http.paths[0].path
      equals: /orders
    - id: ingress-path-type
      type: jsonpath-equals
      points: 1
      object:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: orders-ingress
      path: $.spec.rules[0].http.paths[0].pathType
      equals: Prefix
    - id: ingress-backend-service
      type: jsonpath-equals
      points: 1
      object:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: orders-ingress
      path: $.spec.rules[0].http.paths[0].backend.service.name
      equals: orders-svc
    - id: ingress-backend-port
      type: jsonpath-equals
      points: 1
      object:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: orders-ingress
      path: $.spec.rules[0].http.paths[0].backend.service.port.number
      equals: 8080
